global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Media;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using UserControl = System.Windows.Controls.UserControl;
global using Timer = System.Threading.Timer;
global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using MessageBox = System.Windows.MessageBox;
global using Color = System.Windows.Media.Color;